// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `databaseCommon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __D__project_front850_generated_databaseCommon_h__
#define __D__project_front850_generated_databaseCommon_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace sduept
{

namespace database
{

namespace common
{

class JsonSql;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::sduept::database::common::JsonSql>&);
::IceProxy::Ice::Object* upCast(::IceProxy::sduept::database::common::JsonSql*);

}

}

}

}

namespace sduept
{

namespace database
{

namespace common
{

class JsonSql;
bool operator==(const JsonSql&, const JsonSql&);
bool operator<(const JsonSql&, const JsonSql&);
::Ice::Object* upCast(::sduept::database::common::JsonSql*);
typedef ::IceInternal::Handle< ::sduept::database::common::JsonSql> JsonSqlPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::sduept::database::common::JsonSql> JsonSqlPrx;
void __patch(JsonSqlPtr&, const ::Ice::ObjectPtr&);

}

}

}

namespace sduept
{

namespace database
{

namespace common
{

class DatabaseError : public ::Ice::UserException
{
public:

    DatabaseError() {}
    explicit DatabaseError(const ::std::string&);
    virtual ~DatabaseError() throw();

    virtual ::std::string ice_name() const;
    virtual DatabaseError* ice_clone() const;
    virtual void ice_throw() const;

    ::std::string reason;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::UserException::__writeImpl;
    using ::Ice::UserException::__readImpl;
};

static DatabaseError __DatabaseError_init;

}

}

}

namespace Ice
{
template<>
struct StreamableTraits< ::sduept::database::common::DatabaseError>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

}

namespace sduept
{

namespace database
{

namespace common
{

class Callback_JsonSql_execute_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_JsonSql_execute_Base> Callback_JsonSql_executePtr;

class Callback_JsonSql_query_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_JsonSql_query_Base> Callback_JsonSql_queryPtr;

}

}

}

namespace IceProxy
{

namespace sduept
{

namespace database
{

namespace common
{

class JsonSql : virtual public ::IceProxy::Ice::Object
{
public:

    bool execute(const ::std::string& __p_sql)
    {
        return execute(__p_sql, 0);
    }
    bool execute(const ::std::string& __p_sql, const ::Ice::Context& __ctx)
    {
        return execute(__p_sql, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_execute(const ::std::string& __p_sql, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_execute(__p_sql, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_execute(const ::std::string& __p_sql, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_execute(__p_sql, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_execute(const ::std::string& __p_sql, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_execute(__p_sql, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_execute(const ::std::string& __p_sql, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_execute(__p_sql, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_execute(const ::std::string& __p_sql, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& __p_sql)
    {
        return begin_execute(__p_sql, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& __p_sql, const ::Ice::Context& __ctx)
    {
        return begin_execute(__p_sql, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& __p_sql, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_execute(__p_sql, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& __p_sql, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_execute(__p_sql, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& __p_sql, const ::sduept::database::common::Callback_JsonSql_executePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_execute(__p_sql, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& __p_sql, const ::Ice::Context& __ctx, const ::sduept::database::common::Callback_JsonSql_executePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_execute(__p_sql, &__ctx, __del, __cookie);
    }

    bool end_execute(const ::Ice::AsyncResultPtr&);
    
private:

    bool execute(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_execute(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::std::string query(const ::std::string& __p_sql)
    {
        return query(__p_sql, 0);
    }
    ::std::string query(const ::std::string& __p_sql, const ::Ice::Context& __ctx)
    {
        return query(__p_sql, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_query(const ::std::string& __p_sql, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_query(__p_sql, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_query(const ::std::string& __p_sql, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_query(__p_sql, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_query(const ::std::string& __p_sql, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_query(__p_sql, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_query(const ::std::string& __p_sql, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_query(__p_sql, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_query(const ::std::string& __p_sql, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_query(const ::std::string& __p_sql)
    {
        return begin_query(__p_sql, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_query(const ::std::string& __p_sql, const ::Ice::Context& __ctx)
    {
        return begin_query(__p_sql, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_query(const ::std::string& __p_sql, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_query(__p_sql, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_query(const ::std::string& __p_sql, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_query(__p_sql, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_query(const ::std::string& __p_sql, const ::sduept::database::common::Callback_JsonSql_queryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_query(__p_sql, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_query(const ::std::string& __p_sql, const ::Ice::Context& __ctx, const ::sduept::database::common::Callback_JsonSql_queryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_query(__p_sql, &__ctx, __del, __cookie);
    }

    ::std::string end_query(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string query(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_query(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<JsonSql> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_secure(bool __secure) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_twoway() const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_oneway() const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_batchOneway() const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_datagram() const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_batchDatagram() const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_compress(bool __compress) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_timeout(int __timeout) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<JsonSql> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<JsonSql*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

}

}

namespace sduept
{

namespace database
{

namespace common
{

class JsonSql : virtual public ::Ice::Object
{
public:

    typedef JsonSqlPrx ProxyType;
    typedef JsonSqlPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual bool execute(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___execute(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string query(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___query(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const JsonSql& l, const JsonSql& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const JsonSql& l, const JsonSql& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

}

}

namespace sduept
{

namespace database
{

namespace common
{

template<class T>
class CallbackNC_JsonSql_execute : public Callback_JsonSql_execute_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_JsonSql_execute(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::sduept::database::common::JsonSqlPrx __proxy = ::sduept::database::common::JsonSqlPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_execute(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_JsonSql_executePtr
newCallback_JsonSql_execute(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JsonSql_execute<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_JsonSql_executePtr
newCallback_JsonSql_execute(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JsonSql_execute<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_JsonSql_execute : public Callback_JsonSql_execute_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_JsonSql_execute(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::sduept::database::common::JsonSqlPrx __proxy = ::sduept::database::common::JsonSqlPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_execute(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_JsonSql_executePtr
newCallback_JsonSql_execute(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JsonSql_execute<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_JsonSql_executePtr
newCallback_JsonSql_execute(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JsonSql_execute<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_JsonSql_query : public Callback_JsonSql_query_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_JsonSql_query(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::sduept::database::common::JsonSqlPrx __proxy = ::sduept::database::common::JsonSqlPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_query(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_JsonSql_queryPtr
newCallback_JsonSql_query(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JsonSql_query<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_JsonSql_queryPtr
newCallback_JsonSql_query(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_JsonSql_query<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_JsonSql_query : public Callback_JsonSql_query_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_JsonSql_query(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::sduept::database::common::JsonSqlPrx __proxy = ::sduept::database::common::JsonSqlPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_query(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_JsonSql_queryPtr
newCallback_JsonSql_query(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JsonSql_query<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_JsonSql_queryPtr
newCallback_JsonSql_query(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_JsonSql_query<T, CT>(instance, cb, excb, sentcb);
}

}

}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
