// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `databaseCommon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <databaseCommon.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

namespace
{

namespace
{

const ::std::string __sduept__database__common__JsonSql__execute_name = "execute";

const ::std::string __sduept__database__common__JsonSql__query_name = "query";

}

}

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::sduept::database::common::DatabaseError> __sduept__database__common__DatabaseError_init("::sduept::database::common::DatabaseError");

}

sduept::database::common::DatabaseError::DatabaseError(const ::std::string& __ice_reason) :
    ::Ice::UserException(),
    reason(__ice_reason)
{
}

sduept::database::common::DatabaseError::~DatabaseError() throw()
{
}

::std::string
sduept::database::common::DatabaseError::ice_name() const
{
    return "sduept::database::common::DatabaseError";
}

sduept::database::common::DatabaseError*
sduept::database::common::DatabaseError::ice_clone() const
{
    return new DatabaseError(*this);
}

void
sduept::database::common::DatabaseError::ice_throw() const
{
    throw *this;
}

void
sduept::database::common::DatabaseError::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice("::sduept::database::common::DatabaseError", -1, true);
    __os->write(reason);
    __os->endWriteSlice();
}

void
sduept::database::common::DatabaseError::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->read(reason);
    __is->endReadSlice();
}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::sduept::database::common::upCast(::IceProxy::sduept::database::common::JsonSql* p) { return p; }

void
::IceProxy::sduept::database::common::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::sduept::database::common::JsonSql>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::sduept::database::common::JsonSql;
        v->__copyFrom(proxy);
    }
}

bool
IceProxy::sduept::database::common::JsonSql::execute(const ::std::string& __p_sql, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__sduept__database__common__JsonSql__execute_name);
    ::IceInternal::Outgoing __og(this, __sduept__database__common__JsonSql__execute_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_sql);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::sduept::database::common::DatabaseError&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    bool __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::sduept::database::common::JsonSql::begin_execute(const ::std::string& __p_sql, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__sduept__database__common__JsonSql__execute_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __sduept__database__common__JsonSql__execute_name, __del, __cookie);
    try
    {
        __result->prepare(__sduept__database__common__JsonSql__execute_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_sql);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::sduept::database::common::JsonSql::__begin_execute(const ::std::string& __p_sql, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::sduept::database::common::JsonSqlPrx __proxy = ::sduept::database::common::JsonSqlPrx::uncheckedCast(__result->getProxy());
            bool __ret;
            try
            {
                __ret = __proxy->end_execute(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (bool)> _response;
    };
    return begin_execute(__p_sql, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

bool
IceProxy::sduept::database::common::JsonSql::end_execute(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __sduept__database__common__JsonSql__execute_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::sduept::database::common::DatabaseError&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

::std::string
IceProxy::sduept::database::common::JsonSql::query(const ::std::string& __p_sql, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__sduept__database__common__JsonSql__query_name);
    ::IceInternal::Outgoing __og(this, __sduept__database__common__JsonSql__query_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_sql);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::sduept::database::common::DatabaseError&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::std::string __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::sduept::database::common::JsonSql::begin_query(const ::std::string& __p_sql, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__sduept__database__common__JsonSql__query_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __sduept__database__common__JsonSql__query_name, __del, __cookie);
    try
    {
        __result->prepare(__sduept__database__common__JsonSql__query_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_sql);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::sduept::database::common::JsonSql::__begin_query(const ::std::string& __p_sql, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::sduept::database::common::JsonSqlPrx __proxy = ::sduept::database::common::JsonSqlPrx::uncheckedCast(__result->getProxy());
            ::std::string __ret;
            try
            {
                __ret = __proxy->end_query(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::std::string&)> _response;
    };
    return begin_query(__p_sql, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::std::string
IceProxy::sduept::database::common::JsonSql::end_query(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __sduept__database__common__JsonSql__query_name);
    ::std::string __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::sduept::database::common::DatabaseError&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::sduept::database::common::JsonSql::ice_staticId()
{
    return ::sduept::database::common::JsonSql::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::sduept::database::common::JsonSql::__newInstance() const
{
    return new JsonSql;
}

::Ice::Object* sduept::database::common::upCast(::sduept::database::common::JsonSql* p) { return p; }

namespace
{
const ::std::string __sduept__database__common__JsonSql_ids[2] =
{
    "::Ice::Object",
    "::sduept::database::common::JsonSql"
};

}

bool
sduept::database::common::JsonSql::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__sduept__database__common__JsonSql_ids, __sduept__database__common__JsonSql_ids + 2, _s);
}

::std::vector< ::std::string>
sduept::database::common::JsonSql::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__sduept__database__common__JsonSql_ids[0], &__sduept__database__common__JsonSql_ids[2]);
}

const ::std::string&
sduept::database::common::JsonSql::ice_id(const ::Ice::Current&) const
{
    return __sduept__database__common__JsonSql_ids[1];
}

const ::std::string&
sduept::database::common::JsonSql::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::sduept::database::common::JsonSql";
    return typeId;
#else
    return __sduept__database__common__JsonSql_ids[1];
#endif
}

::Ice::DispatchStatus
sduept::database::common::JsonSql::___execute(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string __p_sql;
    __is->read(__p_sql);
    __inS.endReadParams();
    try
    {
        bool __ret = execute(__p_sql, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::sduept::database::common::DatabaseError& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
sduept::database::common::JsonSql::___query(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string __p_sql;
    __is->read(__p_sql);
    __inS.endReadParams();
    try
    {
        ::std::string __ret = query(__p_sql, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::sduept::database::common::DatabaseError& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

namespace
{
const ::std::string __sduept__database__common__JsonSql_all[] =
{
    "execute",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "query"
};

}

::Ice::DispatchStatus
sduept::database::common::JsonSql::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__sduept__database__common__JsonSql_all, __sduept__database__common__JsonSql_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __sduept__database__common__JsonSql_all)
    {
        case 0:
        {
            return ___execute(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___query(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
sduept::database::common::JsonSql::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
sduept::database::common::JsonSql::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
sduept::database::common::__patch(JsonSqlPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::sduept::database::common::JsonSqlPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::sduept::database::common::JsonSql::ice_staticId(), v);
    }
}
