// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Printer.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __demo__Printer__printString_name = "printString";

}
::IceProxy::Ice::Object* ::IceProxy::demo::upCast(::IceProxy::demo::Printer* p) { return p; }

void
::IceProxy::demo::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::demo::Printer>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::demo::Printer;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::demo::Printer::printString(const ::std::string& __p_s, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __demo__Printer__printString_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_s);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::demo::Printer::begin_printString(const ::std::string& __p_s, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __demo__Printer__printString_name, __del, __cookie);
    try
    {
        __result->prepare(__demo__Printer__printString_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_s);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::demo::Printer::end_printString(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __demo__Printer__printString_name);
}

const ::std::string&
IceProxy::demo::Printer::ice_staticId()
{
    return ::demo::Printer::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::demo::Printer::__newInstance() const
{
    return new Printer;
}

::Ice::Object* demo::upCast(::demo::Printer* p) { return p; }

namespace
{
const ::std::string __demo__Printer_ids[2] =
{
    "::Ice::Object",
    "::demo::Printer"
};

}

bool
demo::Printer::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__demo__Printer_ids, __demo__Printer_ids + 2, _s);
}

::std::vector< ::std::string>
demo::Printer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__demo__Printer_ids[0], &__demo__Printer_ids[2]);
}

const ::std::string&
demo::Printer::ice_id(const ::Ice::Current&) const
{
    return __demo__Printer_ids[1];
}

const ::std::string&
demo::Printer::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::demo::Printer";
    return typeId;
#else
    return __demo__Printer_ids[1];
#endif
}

::Ice::DispatchStatus
demo::Printer::___printString(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string __p_s;
    __is->read(__p_s);
    __inS.endReadParams();
    printString(__p_s, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __demo__Printer_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "printString"
};

}

::Ice::DispatchStatus
demo::Printer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__demo__Printer_all, __demo__Printer_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __demo__Printer_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___printString(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
demo::Printer::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
demo::Printer::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
demo::__patch(PrinterPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::demo::PrinterPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::demo::Printer::ice_staticId(), v);
    }
}
