// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CatalogIndexList.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


// Freeze types in this file:
// name="Freeze::CatalogIndexList", key="string", value="Ice::StringSeq"

#ifndef __CatalogIndexList_h__
#define __CatalogIndexList_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Freeze/Map.h>
#include <Ice/BuiltinSequences.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifndef FREEZE_API
#   ifdef FREEZE_API_EXPORTS
#       define FREEZE_API ICE_DECLSPEC_EXPORT
#   elif defined(ICE_STATIC_LIBS)
#       define FREEZE_API /**/
#   else
#       define FREEZE_API ICE_DECLSPEC_IMPORT
#   endif
#endif

namespace Freeze
{

class FREEZE_API CatalogIndexList : public Freeze::Map< ::std::string, ::Ice::StringSeq, ::Freeze::MapKeyCodec< ::std::string >, ::Freeze::MapValueCodec< ::Ice::StringSeq >, Freeze::IceEncodingCompare >
{
public:


    CatalogIndexList(const Freeze::ConnectionPtr&, const std::string&, bool = true, const Freeze::IceEncodingCompare& = Freeze::IceEncodingCompare());

    template <class _InputIterator>
    CatalogIndexList(const Freeze::ConnectionPtr& __connection, const std::string& __dbName, bool __createDb, _InputIterator __first, _InputIterator __last, const Freeze::IceEncodingCompare& __compare = Freeze::IceEncodingCompare())
        : Freeze::Map< ::std::string, ::Ice::StringSeq, ::Freeze::MapKeyCodec< ::std::string >, ::Freeze::MapValueCodec< ::Ice::StringSeq >, Freeze::IceEncodingCompare >(__connection, __dbName, keyTypeId(), valueTypeId(), __createDb, __first, __last, __compare)
    {
    }

    static std::string keyTypeId();
    static std::string valueTypeId();
};

}

#include <IceUtil/PopDisableWarnings.h>
#endif
