// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `PluginFacade.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __IceGrid_PluginFacade_h__
#define __IceGrid_PluginFacade_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <Ice/IncomingAsync.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/SlicedDataF.h>
#include <Ice/BuiltinSequences.h>
#include <Ice/Current.h>
#include <IceGrid/Admin.h>
#include <IceUtil/UndefSysMacros.h>
#include <IceGrid/Config.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifndef ICE_GRID_API
#   ifdef ICE_GRID_API_EXPORTS
#       define ICE_GRID_API ICE_DECLSPEC_EXPORT
#   elif defined(ICE_STATIC_LIBS)
#       define ICE_GRID_API /**/
#   else
#       define ICE_GRID_API ICE_DECLSPEC_IMPORT
#   endif
#endif

namespace IceProxy
{

}

namespace IceGrid
{

class ReplicaGroupFilter;
bool operator==(const ReplicaGroupFilter&, const ReplicaGroupFilter&);
bool operator<(const ReplicaGroupFilter&, const ReplicaGroupFilter&);
ICE_GRID_API ::Ice::LocalObject* upCast(::IceGrid::ReplicaGroupFilter*);
typedef ::IceInternal::Handle< ::IceGrid::ReplicaGroupFilter> ReplicaGroupFilterPtr;

class TypeFilter;
bool operator==(const TypeFilter&, const TypeFilter&);
bool operator<(const TypeFilter&, const TypeFilter&);
ICE_GRID_API ::Ice::LocalObject* upCast(::IceGrid::TypeFilter*);
typedef ::IceInternal::Handle< ::IceGrid::TypeFilter> TypeFilterPtr;

class RegistryPluginFacade;
bool operator==(const RegistryPluginFacade&, const RegistryPluginFacade&);
bool operator<(const RegistryPluginFacade&, const RegistryPluginFacade&);
ICE_GRID_API ::Ice::LocalObject* upCast(::IceGrid::RegistryPluginFacade*);
typedef ::IceInternal::Handle< ::IceGrid::RegistryPluginFacade> RegistryPluginFacadePtr;

}

namespace IceAsync
{

}

namespace IceProxy
{

}

namespace IceGrid
{

class ICE_GRID_API ReplicaGroupFilter : virtual public ::Ice::LocalObject
{
public:

    typedef ReplicaGroupFilterPtr PointerType;

    virtual ::Ice::StringSeq filter(const ::std::string&, const ::Ice::StringSeq&, const ::Ice::ConnectionPtr&, const ::Ice::Context&) = 0;
};

inline bool operator==(const ReplicaGroupFilter& l, const ReplicaGroupFilter& r)
{
    return static_cast<const ::Ice::LocalObject&>(l) == static_cast<const ::Ice::LocalObject&>(r);
}

inline bool operator<(const ReplicaGroupFilter& l, const ReplicaGroupFilter& r)
{
    return static_cast<const ::Ice::LocalObject&>(l) < static_cast<const ::Ice::LocalObject&>(r);
}

class ICE_GRID_API TypeFilter : virtual public ::Ice::LocalObject
{
public:

    typedef TypeFilterPtr PointerType;

    virtual ::Ice::ObjectProxySeq filter(const ::std::string&, const ::Ice::ObjectProxySeq&, const ::Ice::ConnectionPtr&, const ::Ice::Context&) = 0;
};

inline bool operator==(const TypeFilter& l, const TypeFilter& r)
{
    return static_cast<const ::Ice::LocalObject&>(l) == static_cast<const ::Ice::LocalObject&>(r);
}

inline bool operator<(const TypeFilter& l, const TypeFilter& r)
{
    return static_cast<const ::Ice::LocalObject&>(l) < static_cast<const ::Ice::LocalObject&>(r);
}

class ICE_GRID_API RegistryPluginFacade : virtual public ::Ice::LocalObject
{
public:

    typedef RegistryPluginFacadePtr PointerType;

    virtual ::IceGrid::ApplicationInfo getApplicationInfo(const ::std::string&) const = 0;

    virtual ::IceGrid::ServerInfo getServerInfo(const ::std::string&) const = 0;

    virtual ::std::string getAdapterServer(const ::std::string&) const = 0;

    virtual ::std::string getAdapterApplication(const ::std::string&) const = 0;

    virtual ::std::string getAdapterNode(const ::std::string&) const = 0;

    virtual ::IceGrid::AdapterInfoSeq getAdapterInfo(const ::std::string&) const = 0;

    virtual ::IceGrid::ObjectInfo getObjectInfo(const ::Ice::Identity&) const = 0;

    virtual ::IceGrid::NodeInfo getNodeInfo(const ::std::string&) const = 0;

    virtual ::IceGrid::LoadInfo getNodeLoad(const ::std::string&) const = 0;

    virtual ::std::string getPropertyForAdapter(const ::std::string&, const ::std::string&) const = 0;

    virtual void addReplicaGroupFilter(const ::std::string&, const ::IceGrid::ReplicaGroupFilterPtr&) = 0;

    virtual bool removeReplicaGroupFilter(const ::std::string&, const ::IceGrid::ReplicaGroupFilterPtr&) = 0;

    virtual void addTypeFilter(const ::std::string&, const ::IceGrid::TypeFilterPtr&) = 0;

    virtual bool removeTypeFilter(const ::std::string&, const ::IceGrid::TypeFilterPtr&) = 0;
};

inline bool operator==(const RegistryPluginFacade& l, const RegistryPluginFacade& r)
{
    return static_cast<const ::Ice::LocalObject&>(l) == static_cast<const ::Ice::LocalObject&>(r);
}

inline bool operator<(const RegistryPluginFacade& l, const RegistryPluginFacade& r)
{
    return static_cast<const ::Ice::LocalObject&>(l) < static_cast<const ::Ice::LocalObject&>(r);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
