// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Query.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __IceGrid_Query_h__
#define __IceGrid_Query_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/Identity.h>
#include <Ice/BuiltinSequences.h>
#include <IceGrid/Exception.h>
#include <IceUtil/UndefSysMacros.h>
#include <IceGrid/Config.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifndef ICE_GRID_API
#   ifdef ICE_GRID_API_EXPORTS
#       define ICE_GRID_API ICE_DECLSPEC_EXPORT
#   elif defined(ICE_STATIC_LIBS)
#       define ICE_GRID_API /**/
#   else
#       define ICE_GRID_API ICE_DECLSPEC_IMPORT
#   endif
#endif

namespace IceProxy
{

namespace IceGrid
{

class Query;
ICE_GRID_API void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::IceGrid::Query>&);
ICE_GRID_API ::IceProxy::Ice::Object* upCast(::IceProxy::IceGrid::Query*);

}

}

namespace IceGrid
{

class Query;
bool operator==(const Query&, const Query&);
bool operator<(const Query&, const Query&);
ICE_GRID_API ::Ice::Object* upCast(::IceGrid::Query*);
typedef ::IceInternal::Handle< ::IceGrid::Query> QueryPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::IceGrid::Query> QueryPrx;
ICE_GRID_API void __patch(QueryPtr&, const ::Ice::ObjectPtr&);

}

namespace IceGrid
{

enum LoadSample
{
    LoadSample1,
    LoadSample5,
    LoadSample15
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::IceGrid::LoadSample>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 2;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

}

namespace IceGrid
{

class Callback_Query_findObjectById_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Query_findObjectById_Base> Callback_Query_findObjectByIdPtr;

class Callback_Query_findObjectByType_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Query_findObjectByType_Base> Callback_Query_findObjectByTypePtr;

class Callback_Query_findObjectByTypeOnLeastLoadedNode_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Query_findObjectByTypeOnLeastLoadedNode_Base> Callback_Query_findObjectByTypeOnLeastLoadedNodePtr;

class Callback_Query_findAllObjectsByType_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Query_findAllObjectsByType_Base> Callback_Query_findAllObjectsByTypePtr;

class Callback_Query_findAllReplicas_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Query_findAllReplicas_Base> Callback_Query_findAllReplicasPtr;

}

namespace IceProxy
{

namespace IceGrid
{

class ICE_GRID_API Query : virtual public ::IceProxy::Ice::Object
{
public:

    ::Ice::ObjectPrx findObjectById(const ::Ice::Identity& __p_id)
    {
        return findObjectById(__p_id, 0);
    }
    ::Ice::ObjectPrx findObjectById(const ::Ice::Identity& __p_id, const ::Ice::Context& __ctx)
    {
        return findObjectById(__p_id, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_findObjectById(const ::Ice::Identity& __p_id, const ::IceInternal::Function<void (const ::Ice::ObjectPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findObjectById(__p_id, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findObjectById(const ::Ice::Identity& __p_id, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findObjectById(__p_id, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_findObjectById(const ::Ice::Identity& __p_id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::ObjectPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findObjectById(__p_id, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findObjectById(const ::Ice::Identity& __p_id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findObjectById(__p_id, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_findObjectById(const ::Ice::Identity& __p_id, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Ice::ObjectPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_findObjectById(const ::Ice::Identity& __p_id)
    {
        return begin_findObjectById(__p_id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findObjectById(const ::Ice::Identity& __p_id, const ::Ice::Context& __ctx)
    {
        return begin_findObjectById(__p_id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findObjectById(const ::Ice::Identity& __p_id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectById(__p_id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjectById(const ::Ice::Identity& __p_id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectById(__p_id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjectById(const ::Ice::Identity& __p_id, const ::IceGrid::Callback_Query_findObjectByIdPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectById(__p_id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjectById(const ::Ice::Identity& __p_id, const ::Ice::Context& __ctx, const ::IceGrid::Callback_Query_findObjectByIdPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectById(__p_id, &__ctx, __del, __cookie);
    }

    ::Ice::ObjectPrx end_findObjectById(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::ObjectPrx findObjectById(const ::Ice::Identity&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_findObjectById(const ::Ice::Identity&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::ObjectPrx findObjectByType(const ::std::string& __p_type)
    {
        return findObjectByType(__p_type, 0);
    }
    ::Ice::ObjectPrx findObjectByType(const ::std::string& __p_type, const ::Ice::Context& __ctx)
    {
        return findObjectByType(__p_type, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_findObjectByType(const ::std::string& __p_type, const ::IceInternal::Function<void (const ::Ice::ObjectPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findObjectByType(__p_type, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findObjectByType(const ::std::string& __p_type, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findObjectByType(__p_type, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_findObjectByType(const ::std::string& __p_type, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::ObjectPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findObjectByType(__p_type, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findObjectByType(const ::std::string& __p_type, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findObjectByType(__p_type, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_findObjectByType(const ::std::string& __p_type, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Ice::ObjectPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_findObjectByType(const ::std::string& __p_type)
    {
        return begin_findObjectByType(__p_type, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findObjectByType(const ::std::string& __p_type, const ::Ice::Context& __ctx)
    {
        return begin_findObjectByType(__p_type, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findObjectByType(const ::std::string& __p_type, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectByType(__p_type, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjectByType(const ::std::string& __p_type, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectByType(__p_type, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjectByType(const ::std::string& __p_type, const ::IceGrid::Callback_Query_findObjectByTypePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectByType(__p_type, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjectByType(const ::std::string& __p_type, const ::Ice::Context& __ctx, const ::IceGrid::Callback_Query_findObjectByTypePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectByType(__p_type, &__ctx, __del, __cookie);
    }

    ::Ice::ObjectPrx end_findObjectByType(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::ObjectPrx findObjectByType(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_findObjectByType(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::ObjectPrx findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample)
    {
        return findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, 0);
    }
    ::Ice::ObjectPrx findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::Ice::Context& __ctx)
    {
        return findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::IceInternal::Function<void (const ::Ice::ObjectPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::ObjectPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Ice::ObjectPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample)
    {
        return begin_findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::Ice::Context& __ctx)
    {
        return begin_findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::IceGrid::Callback_Query_findObjectByTypeOnLeastLoadedNodePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findObjectByTypeOnLeastLoadedNode(const ::std::string& __p_type, ::IceGrid::LoadSample __p_sample, const ::Ice::Context& __ctx, const ::IceGrid::Callback_Query_findObjectByTypeOnLeastLoadedNodePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findObjectByTypeOnLeastLoadedNode(__p_type, __p_sample, &__ctx, __del, __cookie);
    }

    ::Ice::ObjectPrx end_findObjectByTypeOnLeastLoadedNode(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::ObjectPrx findObjectByTypeOnLeastLoadedNode(const ::std::string&, ::IceGrid::LoadSample, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_findObjectByTypeOnLeastLoadedNode(const ::std::string&, ::IceGrid::LoadSample, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::ObjectProxySeq findAllObjectsByType(const ::std::string& __p_type)
    {
        return findAllObjectsByType(__p_type, 0);
    }
    ::Ice::ObjectProxySeq findAllObjectsByType(const ::std::string& __p_type, const ::Ice::Context& __ctx)
    {
        return findAllObjectsByType(__p_type, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_findAllObjectsByType(const ::std::string& __p_type, const ::IceInternal::Function<void (const ::Ice::ObjectProxySeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findAllObjectsByType(__p_type, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findAllObjectsByType(const ::std::string& __p_type, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findAllObjectsByType(__p_type, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_findAllObjectsByType(const ::std::string& __p_type, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::ObjectProxySeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findAllObjectsByType(__p_type, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findAllObjectsByType(const ::std::string& __p_type, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findAllObjectsByType(__p_type, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_findAllObjectsByType(const ::std::string& __p_type, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Ice::ObjectProxySeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_findAllObjectsByType(const ::std::string& __p_type)
    {
        return begin_findAllObjectsByType(__p_type, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findAllObjectsByType(const ::std::string& __p_type, const ::Ice::Context& __ctx)
    {
        return begin_findAllObjectsByType(__p_type, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findAllObjectsByType(const ::std::string& __p_type, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findAllObjectsByType(__p_type, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findAllObjectsByType(const ::std::string& __p_type, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findAllObjectsByType(__p_type, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findAllObjectsByType(const ::std::string& __p_type, const ::IceGrid::Callback_Query_findAllObjectsByTypePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findAllObjectsByType(__p_type, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findAllObjectsByType(const ::std::string& __p_type, const ::Ice::Context& __ctx, const ::IceGrid::Callback_Query_findAllObjectsByTypePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findAllObjectsByType(__p_type, &__ctx, __del, __cookie);
    }

    ::Ice::ObjectProxySeq end_findAllObjectsByType(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::ObjectProxySeq findAllObjectsByType(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_findAllObjectsByType(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::ObjectProxySeq findAllReplicas(const ::Ice::ObjectPrx& __p_proxy)
    {
        return findAllReplicas(__p_proxy, 0);
    }
    ::Ice::ObjectProxySeq findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::Ice::Context& __ctx)
    {
        return findAllReplicas(__p_proxy, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::IceInternal::Function<void (const ::Ice::ObjectProxySeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findAllReplicas(__p_proxy, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findAllReplicas(__p_proxy, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::ObjectProxySeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_findAllReplicas(__p_proxy, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_findAllReplicas(__p_proxy, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Ice::ObjectProxySeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy)
    {
        return begin_findAllReplicas(__p_proxy, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::Ice::Context& __ctx)
    {
        return begin_findAllReplicas(__p_proxy, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findAllReplicas(__p_proxy, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findAllReplicas(__p_proxy, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::IceGrid::Callback_Query_findAllReplicasPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findAllReplicas(__p_proxy, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_findAllReplicas(const ::Ice::ObjectPrx& __p_proxy, const ::Ice::Context& __ctx, const ::IceGrid::Callback_Query_findAllReplicasPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_findAllReplicas(__p_proxy, &__ctx, __del, __cookie);
    }

    ::Ice::ObjectProxySeq end_findAllReplicas(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::ObjectProxySeq findAllReplicas(const ::Ice::ObjectPrx&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_findAllReplicas(const ::Ice::ObjectPrx&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Query> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_secure(bool __secure) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_twoway() const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_oneway() const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_batchOneway() const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_datagram() const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_batchDatagram() const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_compress(bool __compress) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Query> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Query*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceGrid
{

class ICE_GRID_API Query : virtual public ::Ice::Object
{
public:

    typedef QueryPrx ProxyType;
    typedef QueryPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Ice::ObjectPrx findObjectById(const ::Ice::Identity&, const ::Ice::Current& = ::Ice::Current()) const = 0;
    ::Ice::DispatchStatus ___findObjectById(::IceInternal::Incoming&, const ::Ice::Current&) const;

    virtual ::Ice::ObjectPrx findObjectByType(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const = 0;
    ::Ice::DispatchStatus ___findObjectByType(::IceInternal::Incoming&, const ::Ice::Current&) const;

    virtual ::Ice::ObjectPrx findObjectByTypeOnLeastLoadedNode(const ::std::string&, ::IceGrid::LoadSample, const ::Ice::Current& = ::Ice::Current()) const = 0;
    ::Ice::DispatchStatus ___findObjectByTypeOnLeastLoadedNode(::IceInternal::Incoming&, const ::Ice::Current&) const;

    virtual ::Ice::ObjectProxySeq findAllObjectsByType(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const = 0;
    ::Ice::DispatchStatus ___findAllObjectsByType(::IceInternal::Incoming&, const ::Ice::Current&) const;

    virtual ::Ice::ObjectProxySeq findAllReplicas(const ::Ice::ObjectPrx&, const ::Ice::Current& = ::Ice::Current()) const = 0;
    ::Ice::DispatchStatus ___findAllReplicas(::IceInternal::Incoming&, const ::Ice::Current&) const;

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const Query& l, const Query& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Query& l, const Query& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace IceGrid
{

template<class T>
class CallbackNC_Query_findObjectById : public Callback_Query_findObjectById_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Ice::ObjectPrx&);

    CallbackNC_Query_findObjectById(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::IceGrid::QueryPrx __proxy = ::IceGrid::QueryPrx::uncheckedCast(__result->getProxy());
        ::Ice::ObjectPrx __ret;
        try
        {
            __ret = __proxy->end_findObjectById(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_Query_findObjectByIdPtr
newCallback_Query_findObjectById(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Ice::ObjectPrx&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Query_findObjectById<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Query_findObjectByIdPtr
newCallback_Query_findObjectById(T* instance, void (T::*cb)(const ::Ice::ObjectPrx&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Query_findObjectById<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Query_findObjectById : public Callback_Query_findObjectById_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Ice::ObjectPrx&, const CT&);

    Callback_Query_findObjectById(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::IceGrid::QueryPrx __proxy = ::IceGrid::QueryPrx::uncheckedCast(__result->getProxy());
        ::Ice::ObjectPrx __ret;
        try
        {
            __ret = __proxy->end_findObjectById(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_Query_findObjectByIdPtr
newCallback_Query_findObjectById(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Ice::ObjectPrx&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Query_findObjectById<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Query_findObjectByIdPtr
newCallback_Query_findObjectById(T* instance, void (T::*cb)(const ::Ice::ObjectPrx&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Query_findObjectById<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Query_findObjectByType : public Callback_Query_findObjectByType_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Ice::ObjectPrx&);

    CallbackNC_Query_findObjectByType(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::IceGrid::QueryPrx __proxy = ::IceGrid::QueryPrx::uncheckedCast(__result->getProxy());
        ::Ice::ObjectPrx __ret;
        try
        {
            __ret = __proxy->end_findObjectByType(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_Query_findObjectByTypePtr
newCallback_Query_findObjectByType(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Ice::ObjectPrx&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Query_findObjectByType<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Query_findObjectByTypePtr
newCallback_Query_findObjectByType(T* instance, void (T::*cb)(const ::Ice::ObjectPrx&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Query_findObjectByType<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Query_findObjectByType : public Callback_Query_findObjectByType_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Ice::ObjectPrx&, const CT&);

    Callback_Query_findObjectByType(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::IceGrid::QueryPrx __proxy = ::IceGrid::QueryPrx::uncheckedCast(__result->getProxy());
        ::Ice::ObjectPrx __ret;
        try
        {
            __ret = __proxy->end_findObjectByType(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_Query_findObjectByTypePtr
newCallback_Query_findObjectByType(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Ice::ObjectPrx&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Query_findObjectByType<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Query_findObjectByTypePtr
newCallback_Query_findObjectByType(T* instance, void (T::*cb)(const ::Ice::ObjectPrx&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Query_findObjectByType<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Query_findObjectByTypeOnLeastLoadedNode : public Callback_Query_findObjectByTypeOnLeastLoadedNode_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Ice::ObjectPrx&);

    CallbackNC_Query_findObjectByTypeOnLeastLoadedNode(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::IceGrid::QueryPrx __proxy = ::IceGrid::QueryPrx::uncheckedCast(__result->getProxy());
        ::Ice::ObjectPrx __ret;
        try
        {
            __ret = __proxy->end_findObjectByTypeOnLeastLoadedNode(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_Query_findObjectByTypeOnLeastLoadedNodePtr
newCallback_Query_findObjectByTypeOnLeastLoadedNode(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Ice::ObjectPrx&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Query_findObjectByTypeOnLeastLoadedNode<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Query_findObjectByTypeOnLeastLoadedNodePtr
newCallback_Query_findObjectByTypeOnLeastLoadedNode(T* instance, void (T::*cb)(const ::Ice::ObjectPrx&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Query_findObjectByTypeOnLeastLoadedNode<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Query_findObjectByTypeOnLeastLoadedNode : public Callback_Query_findObjectByTypeOnLeastLoadedNode_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Ice::ObjectPrx&, const CT&);

    Callback_Query_findObjectByTypeOnLeastLoadedNode(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::IceGrid::QueryPrx __proxy = ::IceGrid::QueryPrx::uncheckedCast(__result->getProxy());
        ::Ice::ObjectPrx __ret;
        try
        {
            __ret = __proxy->end_findObjectByTypeOnLeastLoadedNode(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_Query_findObjectByTypeOnLeastLoadedNodePtr
newCallback_Query_findObjectByTypeOnLeastLoadedNode(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Ice::ObjectPrx&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Query_findObjectByTypeOnLeastLoadedNode<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Query_findObjectByTypeOnLeastLoadedNodePtr
newCallback_Query_findObjectByTypeOnLeastLoadedNode(T* instance, void (T::*cb)(const ::Ice::ObjectPrx&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Query_findObjectByTypeOnLeastLoadedNode<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Query_findAllObjectsByType : public Callback_Query_findAllObjectsByType_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Ice::ObjectProxySeq&);

    CallbackNC_Query_findAllObjectsByType(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::IceGrid::QueryPrx __proxy = ::IceGrid::QueryPrx::uncheckedCast(__result->getProxy());
        ::Ice::ObjectProxySeq __ret;
        try
        {
            __ret = __proxy->end_findAllObjectsByType(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_Query_findAllObjectsByTypePtr
newCallback_Query_findAllObjectsByType(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Ice::ObjectProxySeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Query_findAllObjectsByType<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Query_findAllObjectsByTypePtr
newCallback_Query_findAllObjectsByType(T* instance, void (T::*cb)(const ::Ice::ObjectProxySeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Query_findAllObjectsByType<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Query_findAllObjectsByType : public Callback_Query_findAllObjectsByType_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Ice::ObjectProxySeq&, const CT&);

    Callback_Query_findAllObjectsByType(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::IceGrid::QueryPrx __proxy = ::IceGrid::QueryPrx::uncheckedCast(__result->getProxy());
        ::Ice::ObjectProxySeq __ret;
        try
        {
            __ret = __proxy->end_findAllObjectsByType(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_Query_findAllObjectsByTypePtr
newCallback_Query_findAllObjectsByType(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Ice::ObjectProxySeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Query_findAllObjectsByType<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Query_findAllObjectsByTypePtr
newCallback_Query_findAllObjectsByType(T* instance, void (T::*cb)(const ::Ice::ObjectProxySeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Query_findAllObjectsByType<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Query_findAllReplicas : public Callback_Query_findAllReplicas_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Ice::ObjectProxySeq&);

    CallbackNC_Query_findAllReplicas(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::IceGrid::QueryPrx __proxy = ::IceGrid::QueryPrx::uncheckedCast(__result->getProxy());
        ::Ice::ObjectProxySeq __ret;
        try
        {
            __ret = __proxy->end_findAllReplicas(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_Query_findAllReplicasPtr
newCallback_Query_findAllReplicas(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Ice::ObjectProxySeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Query_findAllReplicas<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Query_findAllReplicasPtr
newCallback_Query_findAllReplicas(T* instance, void (T::*cb)(const ::Ice::ObjectProxySeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Query_findAllReplicas<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Query_findAllReplicas : public Callback_Query_findAllReplicas_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Ice::ObjectProxySeq&, const CT&);

    Callback_Query_findAllReplicas(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::IceGrid::QueryPrx __proxy = ::IceGrid::QueryPrx::uncheckedCast(__result->getProxy());
        ::Ice::ObjectProxySeq __ret;
        try
        {
            __ret = __proxy->end_findAllReplicas(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_Query_findAllReplicasPtr
newCallback_Query_findAllReplicas(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Ice::ObjectProxySeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Query_findAllReplicas<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Query_findAllReplicasPtr
newCallback_Query_findAllReplicas(T* instance, void (T::*cb)(const ::Ice::ObjectProxySeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Query_findAllReplicas<T, CT>(instance, cb, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
